version: '3.8'

services:

  db-sql:
    image: postgres:15.2
    container_name: challanger_box
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=box
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sasa
    ports:
      - "5432:5432"


  document-db:
    image: mongo:6.0.4
    restart: always
    container_name: box_documents_users
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: laboratory
      MONGO_INITDB_DATABASE: users
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
